# langgraph_simple_agent.py
# Program demonstrates use of LangGraph for a simple agent with parallel LLM inference.
# It writes to stdout and asks the user to enter a line of text through stdin.
# It fans the input out to TWO LLMs running in parallel:
#   - meta-llama/Llama-3.2-1B-Instruct
#   - Qwen/Qwen2.5-1.5B-Instruct
# After both models respond, their outputs are collected and printed side-by-side.
# The LLMs use Cuda if available, MPS (Apple Silicon) if available, otherwise CPU.
# After the LangGraph graph is created but before it executes, the program
# uses the Mermaid library to write an image of the graph to the file lg_graph.png.
# The program gets both LLMs from Hugging Face and wraps them for LangChain
# using HuggingFacePipeline.
# The code is commented in detail so a reader can understand each step.

# Import necessary libraries
import torch
from pathlib import Path
from transformers import AutoModelForCausalLM, AutoTokenizer, pipeline
from langchain_huggingface import HuggingFacePipeline
from langgraph.graph import StateGraph, START, END
from typing import TypedDict

# Directory of this script, used for saving output files alongside it
SCRIPT_DIR = Path(__file__).parent

# Determine the best available device for inference
# Priority: CUDA (NVIDIA GPU) > MPS (Apple Silicon) > CPU


def get_device():
    """
    Detect and return the best available compute device.
    Returns 'cuda' for NVIDIA GPUs, 'mps' for Apple Silicon, or 'cpu' as fallback.
    """
    if torch.cuda.is_available():
        print("Using CUDA (NVIDIA GPU) for inference")
        return "cuda"
    elif torch.backends.mps.is_available():
        print("Using MPS (Apple Silicon) for inference")
        return "mps"
    else:
        print("Using CPU for inference")
        return "cpu"

# =============================================================================
# STATE DEFINITION
# =============================================================================
# The state is a TypedDict that flows through all nodes in the graph.
# Each node can read from and write to specific fields in the state.
# LangGraph automatically merges the returned dict from each node into the state.


class AgentState(TypedDict):
    """
    State object that flows through the LangGraph nodes.

    Fields:
    - user_input: The text entered by the user (set by get_user_input node)
    - should_exit: Boolean flag indicating if user wants to quit (set by get_user_input node)
    - verbose: When True, each node prints tracing information to stdout.
               Toggled by typing 'verbose' (enable) or 'quiet' (disable).
    - llama_response: The response generated by Llama-3.2-1B-Instruct (set by call_llama node)
    - qwen_response: The response generated by Qwen2.5-1.5B-Instruct (set by call_qwen node)

    State Flow:
    1. Initial state: all fields empty/default
    2. After get_user_input: user_input, should_exit, and verbose are populated
    3. After dispatch_to_models: no state change (passthrough fan-out node)
    4. After call_llama and call_qwen (run in parallel): llama_response and qwen_response populated
    5. After print_responses: state unchanged (node only reads, doesn't write)

    The graph loops continuously (3-way conditional branch from get_user_input):
        get_user_input -> [conditional] -> dispatch_to_models -> call_llama  -+
                              |                                 -> call_qwen  -+-> print_responses -> get_user_input
                              |                                                                             ^
                              +-> get_user_input (empty / verbose / quiet) --------------------------+
                              |
                              +-> END (if user wants to quit)

    Typing 'verbose' enables per-node tracing; typing 'quiet' disables it.
    Both commands, as well as empty input, re-prompt immediately without calling the LLMs.
    """
    user_input: str
    should_exit: bool
    verbose: bool
    llama_response: str
    qwen_response: str


def _load_hf_llm(model_id: str, device: str) -> HuggingFacePipeline:
    """
    Internal helper: download a causal-LM from HuggingFace Hub, build a
    text-generation pipeline, and wrap it for LangChain.

    Args:
        model_id: HuggingFace Hub model identifier (e.g. 'meta-llama/Llama-3.2-1B-Instruct')
        device:   Compute device string ('cuda', 'mps', or 'cpu')

    Returns:
        A HuggingFacePipeline ready for LangChain .invoke() calls.
    """
    print(f"Loading model: {model_id}")
    print("This may take a moment on first run as the model is downloaded...")

    # Load the tokenizer - converts text to tokens the model understands
    tokenizer = AutoTokenizer.from_pretrained(model_id)

    # Load the model with the appropriate dtype for the target device
    model = AutoModelForCausalLM.from_pretrained(
        model_id,
        torch_dtype=torch.float16 if device != "cpu" else torch.float32,
        device_map=device if device == "cuda" else None,
    )

    # Move model to MPS device if using Apple Silicon
    if device == "mps":
        model = model.to(device)

    # Create a text generation pipeline that combines model and tokenizer
    pipe = pipeline(
        "text-generation",
        model=model,
        tokenizer=tokenizer,
        max_new_tokens=256,  # Maximum tokens to generate in response
        do_sample=True,      # Enable sampling for varied responses
        temperature=0.7,     # Controls randomness (lower = more deterministic)
        top_p=0.95,          # Nucleus sampling parameter
        pad_token_id=tokenizer.eos_token_id,  # Suppress pad_token_id warning
    )

    llm = HuggingFacePipeline(pipeline=pipe)
    print(f"  {model_id} loaded successfully!")
    return llm


def create_llama_llm(device: str) -> HuggingFacePipeline:
    """Load meta-llama/Llama-3.2-1B-Instruct and return a LangChain-compatible LLM."""
    return _load_hf_llm("meta-llama/Llama-3.2-1B-Instruct", device)


def create_qwen_llm(device: str) -> HuggingFacePipeline:
    """Load Qwen/Qwen2.5-1.5B-Instruct and return a LangChain-compatible LLM."""
    return _load_hf_llm("Qwen/Qwen2.5-1.5B-Instruct", device)


def create_graph(llama_llm, qwen_llm):
    """
    Create the LangGraph state graph with five nodes:
    1. get_user_input:    Reads input from stdin
    2. dispatch_to_models: Passthrough fan-out node; LangGraph sends it to both
                           call_llama and call_qwen in parallel via two outgoing edges
    3. call_llama:        Sends input to Llama-3.2-1B-Instruct
    4. call_qwen:         Sends input to Qwen2.5-1.5B-Instruct  (parallel with call_llama)
    5. print_responses:   Fan-in node; waits for both models then prints both responses

    Graph structure:
        START -> get_user_input -> [conditional] -> dispatch_to_models -> call_llama  -+
                      ^                 |                              -> call_qwen   -+-> print_responses -+
                      |                 +-> get_user_input (verbose/quiet/empty)                           |
                      |                 +-> END (quit)                                                     |
                      +-----------------------------------------------------------------------------------+

    The graph runs continuously until the user types 'quit', 'exit', or 'q'.
    """

    # =========================================================================
    # NODE 1: get_user_input
    # =========================================================================
    def get_user_input(state: AgentState) -> dict:
        """
        Node that prompts the user for input via stdin.

        Reads state:
            - verbose: Current tracing mode (preserved across iterations)
        Updates state:
            - user_input: The raw text entered by the user
            - should_exit: True if user wants to quit, False otherwise
            - verbose: Updated if user typed 'verbose' or 'quiet'
        """
        verbose = state.get("verbose", False)

        if verbose:
            print(f"[TRACE] Entering node: get_user_input | verbose={verbose}")

        # Display banner before each prompt
        print("\n" + "=" * 50)
        print("Enter your text (or 'quit' to exit):")
        print("=" * 50)

        print("\n> ", end="")
        user_input = input()

        if verbose:
            print(f"[TRACE] get_user_input received: {user_input!r}")

        # Check if user wants to exit
        if user_input.lower() in ['quit', 'exit', 'q']:
            print("Goodbye!")
            return {
                "user_input": user_input,
                "should_exit": True,
                "verbose": verbose,
            }

        # Toggle tracing mode - routing will loop back without calling the LLMs
        if user_input.lower() == "verbose":
            print("[TRACE] Verbose mode enabled.")
            return {
                "user_input": user_input,
                "should_exit": False,
                "verbose": True,
            }

        if user_input.lower() == "quiet":
            print("Verbose mode disabled.")
            return {
                "user_input": user_input,
                "should_exit": False,
                "verbose": False,
            }

        # Empty input - loop back without calling the LLMs
        if not user_input.strip():
            print("Please enter some text.")
            return {
                "user_input": "",
                "should_exit": False,
                "verbose": verbose,
            }

        # Any other input - continue to dispatch_to_models
        if verbose:
            print(f"[TRACE] get_user_input routing to dispatch_to_models")
        return {
            "user_input": user_input,
            "should_exit": False,
            "verbose": verbose,
        }

    # =========================================================================
    # NODE 2: dispatch_to_models
    # =========================================================================
    # Passthrough fan-out node.  It does not modify state; its only purpose
    # is to be the single target of the conditional edge from get_user_input so
    # that LangGraph can then fan out along its two outgoing edges (to call_llama
    # and call_qwen) and execute those branches in parallel.
    def dispatch_to_models(state: AgentState) -> dict:
        """
        Passthrough node that acts as the fan-out point.

        Reads state:
            - verbose: If True, prints tracing information
        Updates state:
            - Nothing (returns empty dict, state unchanged)
        """
        verbose = state.get("verbose", False)
        if verbose:
            print(f"[TRACE] Entering node: dispatch_to_models — fanning out to Llama and Qwen")
        # No state change; LangGraph will branch to both call_llama and call_qwen
        return {}

    # =========================================================================
    # NODE 3: call_llama
    # =========================================================================
    # Runs in parallel with call_qwen.
    # State changes: writes llama_response
    def call_llama(state: AgentState) -> dict:
        """
        Node that invokes Llama-3.2-1B-Instruct with the user's input.

        Reads state:
            - user_input: The text to send to the model
            - verbose: If True, prints tracing information
        Updates state:
            - llama_response: The text generated by Llama
        """
        verbose = state.get("verbose", False)
        if verbose:
            print(f"[TRACE] Entering node: call_llama")

        user_input = state["user_input"]
        prompt = f"User: {user_input}\nAssistant:"

        if verbose:
            print(f"[TRACE] call_llama sending prompt: {prompt!r}")

        print("\n[Llama] Processing...")
        response = llama_llm.invoke(prompt)

        if verbose:
            print(f"[TRACE] call_llama received response ({len(response)} chars)")

        return {"llama_response": response}

    # =========================================================================
    # NODE 4: call_qwen
    # =========================================================================
    # Runs in parallel with call_llama.
    # State changes: writes qwen_response
    def call_qwen(state: AgentState) -> dict:
        """
        Node that invokes Qwen2.5-1.5B-Instruct with the user's input.

        Reads state:
            - user_input: The text to send to the model
            - verbose: If True, prints tracing information
        Updates state:
            - qwen_response: The text generated by Qwen
        """
        verbose = state.get("verbose", False)
        if verbose:
            print(f"[TRACE] Entering node: call_qwen")

        user_input = state["user_input"]
        prompt = f"User: {user_input}\nAssistant:"

        if verbose:
            print(f"[TRACE] call_qwen sending prompt: {prompt!r}")

        print("\n[Qwen] Processing...")
        response = qwen_llm.invoke(prompt)

        if verbose:
            print(f"[TRACE] call_qwen received response ({len(response)} chars)")

        return {"qwen_response": response}

    # =========================================================================
    # NODE 5: print_responses
    # =========================================================================
    # Fan-in node.  LangGraph automatically waits for both call_llama and
    # call_qwen to finish before executing this node, because both have an
    # outgoing edge into it.
    # State changes: none (read-only)
    def print_responses(state: AgentState) -> dict:
        """
        Fan-in node that prints both model responses side-by-side.

        Reads state:
            - llama_response: Response from Llama-3.2-1B-Instruct
            - qwen_response:  Response from Qwen2.5-1.5B-Instruct
            - verbose: If True, prints tracing information
        Updates state:
            - Nothing (returns empty dict, state unchanged)
        """
        verbose = state.get("verbose", False)
        if verbose:
            print(f"[TRACE] Entering node: print_responses (both models finished)")

        print("\n" + "=" * 50)
        print("Llama-3.2-1B-Instruct response:")
        print("-" * 50)
        print(state["llama_response"])

        print("\n" + "=" * 50)
        print("Qwen2.5-1.5B-Instruct response:")
        print("-" * 50)
        print(state["qwen_response"])
        print("=" * 50)

        if verbose:
            print(f"[TRACE] print_responses complete, routing back to get_user_input")

        return {}

    # =========================================================================
    # ROUTING FUNCTION
    # =========================================================================
    def route_after_input(state: AgentState) -> str:
        """
        Routing function that determines the next node based on state.

        Examines state:
            - should_exit: If True, terminate the graph
            - user_input: If empty, 'verbose', or 'quiet', loop back to
                          get_user_input without calling the LLMs

        Returns:
            - END: If user wants to quit
            - "get_user_input": If input is empty or a control command (verbose/quiet)
            - "dispatch_to_models": For any other non-empty input
        """
        if state.get("should_exit", False):
            return END

        user_input = state.get("user_input", "")
        if not user_input.strip() or user_input.lower() in ("verbose", "quiet"):
            return "get_user_input"

        return "dispatch_to_models"

    # =========================================================================
    # GRAPH CONSTRUCTION
    # =========================================================================
    graph_builder = StateGraph(AgentState)

    # Register all five nodes
    graph_builder.add_node("get_user_input",    get_user_input)
    graph_builder.add_node("dispatch_to_models", dispatch_to_models)
    graph_builder.add_node("call_llama",         call_llama)
    graph_builder.add_node("call_qwen",          call_qwen)
    graph_builder.add_node("print_responses",    print_responses)

    # 1. START -> get_user_input
    graph_builder.add_edge(START, "get_user_input")

    # 2. get_user_input -> [conditional] -> dispatch_to_models | get_user_input | END
    graph_builder.add_conditional_edges(
        "get_user_input",
        route_after_input,
        {
            "dispatch_to_models": "dispatch_to_models",
            "get_user_input":     "get_user_input",
            END:                   END,
        }
    )

    # 3. Fan-out: dispatch_to_models -> call_llama  (parallel branch 1)
    #             dispatch_to_models -> call_qwen   (parallel branch 2)
    #    LangGraph executes both branches concurrently.
    graph_builder.add_edge("dispatch_to_models", "call_llama")
    graph_builder.add_edge("dispatch_to_models", "call_qwen")

    # 4. Fan-in: both branches converge on print_responses
    #    LangGraph waits for both call_llama and call_qwen before continuing.
    graph_builder.add_edge("call_llama", "print_responses")
    graph_builder.add_edge("call_qwen",  "print_responses")

    # 5. Loop: print_responses -> get_user_input
    graph_builder.add_edge("print_responses", "get_user_input")

    # Compile the graph into an executable form
    graph = graph_builder.compile()

    return graph


def save_graph_image(graph, filename="lg_graph.png"):
    """
    Generate a Mermaid diagram of the graph and save it as a PNG image.
    Uses the graph's built-in Mermaid export functionality.
    """
    try:
        # Get the Mermaid PNG representation of the graph
        # This requires the 'grandalf' package for rendering
        png_data = graph.get_graph(xray=True).draw_mermaid_png()

        # Save the image in the same directory as this script
        output_path = SCRIPT_DIR / filename
        with open(output_path, "wb") as f:
            f.write(png_data)

        print(f"Graph image saved to {output_path}")
    except Exception as e:
        print(f"Could not save graph image: {e}")
        print("You may need to install additional dependencies: pip install grandalf")


def main():
    """
    Main function that orchestrates the parallel-LLM agent workflow:
    1. Detect the best compute device
    2. Load both LLMs (Llama and Qwen) sequentially to avoid memory contention
    3. Create the LangGraph
    4. Save the graph visualization
    5. Run the graph (it loops internally until user quits)

    Graph node flow per query:
        get_user_input -> dispatch_to_models -> call_llama  -+-> print_responses -> (loop)
                                             -> call_qwen   -+

    The graph only terminates when the user types 'quit', 'exit', or 'q'.
    """
    print("=" * 50)
    print("LangGraph Parallel Agent: Llama-3.2-1B + Qwen2.5-1.5B")
    print("=" * 50)
    print()

    # Step 1: Detect device once; both models will use the same device
    device = get_device()

    # Step 2: Load both LLMs
    print("\nLoading Llama-3.2-1B-Instruct...")
    llama_llm = create_llama_llm(device)

    print("\nLoading Qwen2.5-1.5B-Instruct...")
    qwen_llm = create_qwen_llm(device)

    # Step 3: Build the LangGraph with both LLMs
    print("\nCreating LangGraph...")
    graph = create_graph(llama_llm, qwen_llm)
    print("Graph created successfully!")

    # Step 4: Save a visual representation of the graph before execution
    print("\nSaving graph visualization...")
    save_graph_image(graph)

    # Step 5: Run the graph - it loops internally until the user quits.
    # The graph loops continuously, updating state as it goes:
    #   - get_user_input displays banner, populates user_input and should_exit
    #   - dispatch_to_models fans out to call_llama and call_qwen (run in parallel)
    #   - print_responses waits for both models, then prints llama_response and qwen_response
    #   - print_responses loops back to get_user_input
    initial_state: AgentState = {
        "user_input": "",
        "should_exit": False,
        "verbose": False,
        "llama_response": "",
        "qwen_response": "",
    }

    # Single invocation - the graph loops internally via print_responses -> get_user_input
    # The graph only exits when route_after_input returns END (user typed quit/exit/q)
    graph.invoke(initial_state)


# Entry point - only run main() if this script is executed directly
if __name__ == "__main__":
    main()
